// b-Profiles/myprofile/src/lib/components/MediasView.svelte
<script lang="ts">
  import type { MediaItem, DataItem } from '$lib/types';
  import Icon from './Icon.svelte';

  let { mediaLinks, trackedApps }: { mediaLinks: MediaItem[]; trackedApps: DataItem[] } = $props();
</script>

<div class="footer-links">
  <!-- Social Media Icons -->
  {#each mediaLinks as media}
    <a
      href={media.url}
      target="_blank"
      rel="noopener noreferrer"
      class="footer-link-item"
      style="--link-color: {media.accentColor}"
      title={media.platform}
    >
      <Icon name={media.icon} size={20} />
    </a>
  {/each}

  <span class="footer-divider">//</span>

  <!-- Tracked Apps Icons -->
  {#each trackedApps as app}
    <div
      class="footer-link-item app-item"
      style="--link-color: {app.accentColor}"
      title={app.platform}
    >
      <Icon name={app.icon} size={20} />
    </div>
  {/each}
</div>

// myprofile/src/app/components/MediasView.vue
<script setup lang="ts">
import type { MediaItem } from '~/types'

defineProps<{
  mediaLinks: MediaItem[]
}>()
</script>

<template>
  <div class="medias-container fade-in">
    <div class="medias-header">
      <Icon name="lucide:share-2" class="anim-icon" />
      CONNECT // SOCIAL NETWORKS
    </div>
    <div class="medias-grid">
      <a
        v-for="media in mediaLinks"
        :key="media.id"
        :href="media.url"
        target="_blank"
        rel="noopener noreferrer"
        class="media-item"
        :style="{
          '--media-color': media.accentColor,
          '--media-glow': media.accentColor + '40'
        }"
      >
        <div class="media-icon">
          <Icon :name="'lucide:' + media.icon" :size="28" />
        </div>
        <span class="media-label">{{ media.platform }}</span>
      </a>
    </div>
  </div>
</template>
