// b-Profiles/myprofile/src/lib/components/MediasView.svelte
<script lang="ts">
  import type { MediaItem, DataItem } from '$lib/types';
  import Icon from './Icon.svelte';

  let { mediaLinks, trackedApps }: { mediaLinks: MediaItem[]; trackedApps: DataItem[] } = $props();
</script>

<div class="footer-links">
  <!-- Social Media Icons -->
  {#each mediaLinks as media}
    <a
      href={media.url}
      target="_blank"
      rel="noopener noreferrer"
      class="footer-link-item"
      style="--link-color: {media.accentColor}"
      title={media.platform}
    >
      <Icon name={media.icon} size={20} />
    </a>
  {/each}

  <span class="footer-divider">//</span>

  <!-- Tracked Apps Icons -->
  {#each trackedApps as app}
    <div
      class="footer-link-item app-item"
      style="--link-color: {app.accentColor}"
      title={app.platform}
    >
      <Icon name={app.icon} size={20} />
    </div>
  {/each}
</div>

// c_Personal_Profiles/myprofile/src/app/components/MediasView.vue
<script setup lang="ts">
import type { MediaItem, DataItem } from '~/types'

defineProps<{
  mediaLinks: MediaItem[]
  trackedApps: DataItem[]
}>()
</script>

<template>
  <div class="footer-links">
    <!-- Social Media Icons -->
    <a
      v-for="media in mediaLinks"
      :key="media.id"
      :href="media.url"
      target="_blank"
      rel="noopener noreferrer"
      class="footer-link-item"
      :style="{ '--link-color': media.accentColor }"
      :title="media.platform"
    >
      <Icon :name="'lucide:' + media.icon" :size="20" />
    </a>

    <span class="footer-divider">//</span>

    <!-- Tracked Apps Icons -->
    <div
      v-for="app in trackedApps"
      :key="app.id"
      class="footer-link-item app-item"
      :style="{ '--link-color': app.accentColor }"
      :title="app.platform"
    >
      <Icon :name="'lucide:' + app.icon" :size="20" />
    </div>
  </div>
</template>
