// c_Personal_Profiles/myprofile/src/lib/components/SphereView.svelte
<script lang="ts">
  import type { Rotation } from '$lib/types';
  import Icon from './Icon.svelte';

  let {
    rotation,
    onMouseDown,
    onMouseMove,
    onMouseUp,
    onTouchStart,
    onTouchMove,
    onTouchEnd
  }: {
    rotation: Rotation;
    onMouseDown: (e: MouseEvent) => void;
    onMouseMove: (e: MouseEvent) => void;
    onMouseUp: () => void;
    onTouchStart: (e: TouchEvent) => void;
    onTouchMove: (e: TouchEvent) => void;
    onTouchEnd: () => void;
  } = $props();

  // Realistic Solar System Data
  const planets = [
    { id: 'mercury', name: 'MERCURY', color: '#b5b5b5', size: 8, orbit: 60, speed: 8, tilt: 7 },
    { id: 'venus', name: 'VENUS', color: '#e6c87a', size: 12, orbit: 90, speed: 12, tilt: 3.4 },
    { id: 'earth', name: 'EARTH', color: '#6b93d6', size: 13, orbit: 120, speed: 16, tilt: 23.4 },
    { id: 'mars', name: 'MARS', color: '#c1440e', size: 10, orbit: 150, speed: 20, tilt: 25.2 },
    { id: 'jupiter', name: 'JUPITER', color: '#d8ca9d', size: 28, orbit: 195, speed: 28, tilt: 3.1 },
    { id: 'saturn', name: 'SATURN', color: '#f4d59e', size: 24, orbit: 245, speed: 36, tilt: 26.7, hasRings: true },
    { id: 'uranus', name: 'URANUS', color: '#d1e7e7', size: 16, orbit: 285, speed: 48, tilt: 97.8 },
    { id: 'neptune', name: 'NEPTUNE', color: '#5b5ddf', size: 15, orbit: 320, speed: 60, tilt: 28.3 }
  ];

  // Generate asteroids
  const asteroids = Array.from({ length: 40 }, (_, n) => ({
    angle: (n * 9) + 'deg',
    distance: (165 + Math.random() * 20) + 'px',
    size: (1 + Math.random() * 2) + 'px',
    delay: (Math.random() * 30) + 's'
  }));

  // Generate stars
  const stars = Array.from({ length: 80 }, () => ({
    x: (Math.random() * 800 - 400) + 'px',
    y: (Math.random() * 800 - 400) + 'px',
    z: (Math.random() * 300 - 150) + 'px',
    twinkleDelay: (Math.random() * 4) + 's',
    size: (Math.random() * 2 + 0.5) + 'px'
  }));

  function handleTouchMove(e: TouchEvent) {
    e.preventDefault();
    onTouchMove(e);
  }
</script>

<div
  class="solar-viewport fade-in"
  onmousedown={onMouseDown}
  onmousemove={onMouseMove}
  onmouseup={onMouseUp}
  onmouseleave={onMouseUp}
  ontouchstart={onTouchStart}
  ontouchmove={handleTouchMove}
  ontouchend={onTouchEnd}
  role="application"
  tabindex="0"
>
  <div class="solar-instruction">
    <Icon name="rotate-3d" size={16} class="anim-icon" />
    DRAG TO EXPLORE THE SOLAR SYSTEM
  </div>

  <div
    class="solar-system-scene"
    style="transform: rotateX({rotation.x + 60}deg) rotateZ({rotation.y}deg)"
  >
    <!-- Sun -->
    <div class="sun-star">
      <div class="sun-surface"></div>
      <div class="sun-corona-1"></div>
      <div class="sun-corona-2"></div>
      <div class="sun-glow"></div>
    </div>

    <!-- Orbital Paths -->
    {#each planets as planet}
      <div
        class="orbital-path"
        style="width: {planet.orbit * 2}px; height: {planet.orbit * 2}px"
      ></div>
    {/each}

    <!-- Planets -->
    {#each planets as planet}
      <div
        class="planet-container"
        style="--orbit-radius: {planet.orbit}px; --orbit-speed: {planet.speed}s; --planet-size: {planet.size}px; --planet-color: {planet.color}; --planet-tilt: {planet.tilt}deg"
      >
        <div class="planet-orbit-wrapper">
          <div class="planet-body" class:has-rings={planet.hasRings}>
            <div class="planet-sphere"></div>
            {#if planet.hasRings}
              <div class="saturn-rings"></div>
            {/if}
            <span class="planet-name">{planet.name}</span>
          </div>
        </div>
      </div>
    {/each}

    <!-- Asteroid Belt (between Mars and Jupiter) -->
    <div class="asteroid-belt">
      {#each asteroids as asteroid}
        <div
          class="asteroid"
          style="--angle: {asteroid.angle}; --distance: {asteroid.distance}; --size: {asteroid.size}; --delay: {asteroid.delay}"
        ></div>
      {/each}
    </div>

    <!-- Stars Background -->
    <div class="star-field">
      {#each stars as star}
        <div
          class="distant-star"
          style="--x: {star.x}; --y: {star.y}; --z: {star.z}; --twinkle-delay: {star.twinkleDelay}; --star-size: {star.size}"
        ></div>
      {/each}
    </div>
  </div>
</div>

// b_Linktree/myprofile/src/app/components/SphereView.vue
<script setup lang="ts">
import type { SpherePoint, Rotation } from '~/types'

defineProps<{
  spherePoints: SpherePoint[]
  rotation: Rotation
}>()

defineEmits<{
  (e: 'mousedown', event: MouseEvent): void
  (e: 'mousemove', event: MouseEvent): void
  (e: 'mouseup'): void
  (e: 'mouseleave'): void
  (e: 'touchstart', event: TouchEvent): void
  (e: 'touchmove', event: TouchEvent): void
  (e: 'touchend'): void
}>()

// Calculate orbit radius for each planet (concentric rings)
const getOrbitRadius = (index: number, total: number) => {
  const minRadius = 100
  const maxRadius = 280
  return minRadius + ((index / (total - 1)) * (maxRadius - minRadius))
}

// Get orbit tilt angle for varied orbital planes
const getOrbitTilt = (index: number) => {
  // Each orbit has different tilt for 3D effect
  const tilts = [75, 70, 80, 65, 85, 72]
  return tilts[index % tilts.length]
}

// Get orbit animation speed (inner planets faster)
const getOrbitSpeed = (index: number) => {
  return 12 + index * 4
}

// Get starting rotation offset for each planet
const getOrbitOffset = (index: number) => {
  // Spread planets around their orbits
  return index * 60
}
</script>

<template>
  <div
    class="sphere-viewport fade-in"
    @mousedown="$emit('mousedown', $event)"
    @mousemove="$emit('mousemove', $event)"
    @mouseup="$emit('mouseup')"
    @mouseleave="$emit('mouseleave')"
    @touchstart="$emit('touchstart', $event)"
    @touchmove.prevent="$emit('touchmove', $event)"
    @touchend="$emit('touchend')"
  >
    <div class="sphere-instruction">
      <Icon name="lucide:orbit" class="anim-icon" />
      DRAG TO EXPLORE THE UNIVERSE
    </div>
    <div
      class="sphere-scene solar-system"
      :style="{
        transform: 'rotateX(' + rotation.x + 'deg) rotateY(' + rotation.y + 'deg)'
      }"
    >
      <!-- Central Sun -->
      <div class="sun">
        <div class="sun-core" />
        <div class="sun-corona" />
        <div class="sun-flare" />
      </div>

      <!-- Orbital Rings -->
      <div
        v-for="(pt, index) in spherePoints"
        :key="'orbit-' + pt.id"
        class="orbit-ring"
        :style="{
          width: getOrbitRadius(index, spherePoints.length) * 2 + 'px',
          height: getOrbitRadius(index, spherePoints.length) * 2 + 'px',
          transform: 'translate(-50%, -50%) rotateX(' + getOrbitTilt(index) + 'deg)',
          '--ring-color': pt.accentColor
        }"
      />

      <!-- Planets in orbit -->
      <div
        v-for="(pt, index) in spherePoints"
        :key="pt.id"
        class="planet-orbit"
        :style="{
          animationDuration: getOrbitSpeed(index) + 's',
          transform: 'rotateX(' + getOrbitTilt(index) + 'deg) rotateZ(' + getOrbitOffset(index) + 'deg)'
        }"
      >
        <div
          class="planet"
          :style="{
            transform: 'translateX(' + getOrbitRadius(index, spherePoints.length) + 'px)',
            '--planet-color': pt.accentColor,
            '--planet-glow': pt.accentColor + '60'
          }"
        >
          <div
            class="planet-face"
            :style="{
              transform: 'rotateZ(' + (-getOrbitOffset(index)) + 'deg) rotateX(' + (-getOrbitTilt(index)) + 'deg) rotateX(' + (-rotation.x) + 'deg) rotateY(' + (-rotation.y) + 'deg)'
            }"
          >
            <div class="planet-body" :style="{ borderColor: pt.accentColor, boxShadow: '0 0 20px ' + pt.accentColor + ', inset 0 0 15px ' + pt.accentColor + '40' }">
              <Icon
                :name="'lucide:' + pt.icon"
                :size="22"
                :style="{ color: pt.accentColor }"
              />
            </div>
            <span class="planet-label" :style="{ color: pt.accentColor }">
              {{ pt.platform }}
            </span>
          </div>
        </div>
      </div>

      <!-- Starfield background particles -->
      <div class="starfield">
        <div v-for="n in 50" :key="'star-' + n" class="star" :style="{
          '--x': Math.random() * 600 - 300 + 'px',
          '--y': Math.random() * 600 - 300 + 'px',
          '--z': Math.random() * 400 - 200 + 'px',
          '--delay': Math.random() * 3 + 's',
          '--size': Math.random() * 2 + 1 + 'px'
        }" />
      </div>
    </div>
  </div>
</template>
