// cloud/src_nextjs/components/ViewToggle.tsx
'use client';

import { Icon } from './Icon';
import { icons } from '@/lib/services';

export type ViewType = 'cards' | 'tree' | 'architecture' | 'ai-architecture';

interface ViewToggleProps {
  activeView: ViewType;
  onViewChange: (view: ViewType) => void;
}

const viewGroups = [
  {
    label: 'Services',
    views: [
      { id: 'cards' as ViewType, label: 'Cards', icon: icons.cards },
      { id: 'tree' as ViewType, label: 'Tree', icon: icons.tree },
    ],
  },
  {
    label: 'Architecture',
    views: [
      { id: 'architecture' as ViewType, label: 'Server', icon: icons.architecture },
      { id: 'ai-architecture' as ViewType, label: 'AI', icon: icons.ai },
    ],
  },
];

export function ViewToggle({ activeView, onViewChange }: ViewToggleProps) {
  return (
    <div className="flex flex-wrap items-center justify-center gap-4 mt-6">
      {viewGroups.map((group, idx) => (
        <div key={group.label} className="flex items-center gap-2">
          {idx > 0 && (
            <span className="hidden sm:block w-px h-8 bg-[var(--border-color)] mx-2" />
          )}
          <span className="text-xs text-[var(--text-secondary)] uppercase tracking-wider">
            {group.label}
          </span>
          <div className="flex gap-1 bg-[var(--bg-secondary)] p-1 rounded-[var(--border-radius)]">
            {group.views.map((view) => (
              <button
                key={view.id}
                onClick={() => onViewChange(view.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-[var(--border-radius)]
                           transition-all duration-[var(--transition-speed)]
                           ${
                             activeView === view.id
                               ? 'bg-[var(--accent-primary)] text-black font-bold'
                               : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-card)]'
                           }`}
              >
                <Icon path={view.icon} className="w-4 h-4" />
                {view.label}
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// a_Cloud/cloud/src_vue/src/components/ViewToggle.vue
<script setup lang="ts">
import type { ViewType } from '../lib/types'
import { icons } from '../lib/services'
import SvgIcon from './SvgIcon.vue'

const model = defineModel<ViewType>()

const viewGroups = [
  {
    label: 'Services',
    views: [
      { id: 'cards' as ViewType, label: 'Cards', icon: icons.cards },
      { id: 'tree' as ViewType, label: 'Tree', icon: icons.tree },
    ],
  },
  {
    label: 'Architecture',
    views: [
      { id: 'architecture' as ViewType, label: 'Server', icon: icons.architecture },
      { id: 'ai-architecture' as ViewType, label: 'AI', icon: icons.ai },
    ],
  },
]
</script>

<template>
  <div class="view-toggle">
    <div v-for="(group, idx) in viewGroups" :key="group.label" class="group">
      <span v-if="idx > 0" class="divider" />
      <span class="group-label">{{ group.label }}</span>
      <div class="buttons">
        <button
          v-for="view in group.views"
          :key="view.id"
          @click="model = view.id"
          :class="['view-btn', { active: model === view.id }]"
        >
          <SvgIcon :path="view.icon" class="icon" />
          {{ view.label }}
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.view-toggle {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  gap: 1rem;
  margin-top: 1.5rem;
}

.group {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.divider {
  display: none;
  width: 1px;
  height: 2rem;
  background: var(--border-color);
  margin: 0 0.5rem;
}

@media (min-width: 640px) {
  .divider {
    display: block;
  }
}

.group-label {
  font-size: 0.75rem;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.buttons {
  display: flex;
  gap: 0.25rem;
  background: var(--bg-secondary);
  padding: 0.25rem;
  border-radius: var(--border-radius);
}

.view-btn {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.375rem 0.75rem;
  font-size: 0.875rem;
  border: none;
  border-radius: var(--border-radius);
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all var(--transition-speed);
}

.view-btn:hover {
  color: var(--text-primary);
  background: var(--bg-card);
}

.view-btn.active {
  background: var(--accent-primary);
  color: black;
  font-weight: bold;
}

.icon {
  width: 1rem;
  height: 1rem;
}
</style>
